# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/constant_resolver/all/constant_resolver.rbi
#
# constant_resolver-0.2.0

class ConstantResolver
end
class ConstantResolver::Error < StandardError
end
class ConstantResolver::ConstantContext < Anonymous_Struct_46
end
class ConstantResolver::DefaultInflector
end
