# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/html_tokenizer/all/html_tokenizer.rbi
#
# html_tokenizer-0.0.7

module HtmlTokenizer
end
class HtmlTokenizer::ParserError < RuntimeError
end
