# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/smart_properties/all/smart_properties.rbi
#
# smart_properties-1.17.0

module SmartProperties
end
class SmartProperties::PropertyCollection
  include Enumerable
end
class SmartProperties::Property
end
class SmartProperties::Error < ArgumentError
end
class SmartProperties::ConfigurationError < SmartProperties::Error
end
class SmartProperties::AssignmentError < SmartProperties::Error
end
class SmartProperties::ConstructorArgumentForwardingError < SmartProperties::Error
end
class SmartProperties::MissingValueError < SmartProperties::AssignmentError
end
class SmartProperties::InvalidValueError < SmartProperties::AssignmentError
end
class SmartProperties::InitializationError < SmartProperties::Error
end
module SmartProperties::Validations
end
class SmartProperties::Validations::Ancestor
  extend SmartProperties::ClassMethods
  include Anonymous_Module_45
  include SmartProperties
end
module Anonymous_Module_45
end
module SmartProperties::ClassMethods
end
module SmartProperties::ModuleMethods
end
