# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: strict

module ActionMailbox::InboundEmail::ActiveRelation_WhereNot; end
module ActionMailbox::InboundEmail::CustomFinderMethods; end
module Fiddle::CParser; end
module Fiddle::Importer; end
module RDoc::Task; end
